default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        alias: format
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        alias: format
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        alias: lint
        additional_dependencies:
          - pyflakes==2.4.0
          - pycodestyle==2.8.0
          - mccabe==0.6.1
          - flake8-builtins==1.5.3
          - flake8-bugbear==22.4.25
          - flake8-comprehensions==3.8.0
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
          - flake8-noqa==1.2.1
          - pep8-naming==0.12.1
  - repo: local
    hooks:
      - id: mypy
        alias: lint
        name: mypy
        entry: bash -c 'POETRY_ENV_PATH=$(poetry env info -p) && { [[ ! -z ${POETRY_ENV_PATH} ]] && source ${POETRY_ENV_PATH}/bin/activate; }; mypy "$@"' dummy-first-arg
        language: system
        types:
          - python
        require_serial: true
